version: 2.1

jobs:
  build:
    machine: true
      # image: ubuntu-2004:202010-01

    steps:
      - run:
          name: "Say hello"
          command: |
            ps aux
            whoami
            pwd
            docker ps
            docker images
            cat /etc/hosts
