version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

      steps:
        - checkout
        - run:
            name: "Say hello"
            command: "ps aux"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
